"""Generate src/scyllasband_unicode_tables.inc from Python's unicodedata.

The native text frontend mirrors Python string semantics (str.isalnum, str.lower, regex \\d and \\w,
unicodedata categories and NFC), so its tables come from the same Unicode database as the Python runtime.
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

MAX = 0x110000


def ranges(predicate):
    out, start = [], None
    for cp in range(MAX):
        if predicate(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX - 1))
    return out


def category(cp):
    return unicodedata.category(chr(cp))


def lower_runs():
    single, special = {}, {}
    for cp in range(MAX):
        lowered = chr(cp).lower()
        if lowered == chr(cp):
            continue
        if len(lowered) == 1:
            single[cp] = ord(lowered) - cp
        else:
            special[cp] = lowered
    runs = []
    for cp in sorted(single):
        delta = single[cp]
        if runs:
            lo, hi, stride, run_delta = runs[-1]
            if run_delta == delta and (cp - hi) == stride and (hi > lo or stride in (1, 2)):
                runs[-1] = (lo, cp, stride, delta)
                continue
            if run_delta == delta and lo == hi and cp - hi in (1, 2):
                runs[-1] = (lo, cp, cp - hi, delta)
                continue
        runs.append((cp, cp, 1, delta))
    return runs, special


def decompositions():
    rows = []
    for cp in range(MAX):
        raw = unicodedata.decomposition(chr(cp))
        if not raw or raw.startswith("<"):
            continue
        parts = [int(p, 16) for p in raw.split()]
        first, second = parts[0], parts[1] if len(parts) > 1 else 0
        composes = len(parts) == 2 and unicodedata.normalize("NFC", chr(first) + chr(second)) == chr(cp)
        rows.append((cp, first, second, int(composes)))
    return rows


def ccc_ranges():
    out = []
    for cp in range(MAX):
        value = unicodedata.combining(chr(cp))
        if not value:
            continue
        if out and out[-1][1] == cp - 1 and out[-1][2] == value:
            out[-1] = (out[-1][0], cp, value)
        else:
            out.append((cp, cp, value))
    return out


def emit_pairs(name, items):
    body = ",".join(f"{{0x{lo:X},0x{hi:X}}}" for lo, hi in items)
    return f"static const CodepointRange {name}[] = {{{body}}};\n"


def wrap(text, width=118):
    out, line = [], ""
    for token in text.split(","):
        piece = token + ","
        if len(line) + len(piece) > width:
            out.append(line)
            line = ""
        line += piece
    out.append(line)
    return "\n".join(out).rstrip(",")


def cased(cp):
    char = chr(cp)
    return char.islower() or char.isupper() or char.istitle()


def case_ignorable(cp):
    # Probed through str.lower()'s Final_Sigma handling: an ignorable character is skipped when looking for the
    # cased letter before a capital sigma.
    char = chr(cp)
    return ("A" + char + "\u03a3").lower()[-1] == "\u03c2" and ("1" + char + "\u03a3").lower()[-1] == "\u03c3"


def main() -> None:
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parents[1] / "src" / "scyllasband_unicode_tables.inc"
    alnum = ranges(lambda cp: chr(cp).isalnum())
    decimal = ranges(lambda cp: chr(cp).isdecimal())
    mark = ranges(lambda cp: category(cp).startswith("M"))
    punct_space = ranges(lambda cp: category(cp)[0] in "PZ")
    cased_ranges = ranges(lambda cp: not 0xD800 <= cp <= 0xDFFF and cased(cp))
    ignorable_ranges = ranges(lambda cp: not 0xD800 <= cp <= 0xDFFF and case_ignorable(cp))
    runs, special = lower_runs()
    decomp = decompositions()
    ccc = ccc_ranges()
    parts = [f"// Generated by tools/generate_unicode_tables.py from Unicode {unicodedata.unidata_version}. Do not edit.\n"]
    for name, items in (("kAlnum", alnum), ("kDecimal", decimal), ("kMark", mark), ("kPunctOrSpace", punct_space), ("kCased", cased_ranges),
                        ("kCaseIgnorable", ignorable_ranges)):
        body = ",".join(f"{{0x{lo:X},0x{hi:X}}}" for lo, hi in items)
        parts.append(f"static const CodepointRange {name}[] = {{\n{wrap(body)}}};\n")
    body = ",".join(f"{{0x{lo:X},0x{hi:X},{stride},{delta}}}" for lo, hi, stride, delta in runs)
    parts.append(f"static const LowerRun kLower[] = {{\n{wrap(body)}}};\n")
    body = ",".join("{0x%X,\"%s\"}" % (cp, "".join("\\x%02x" % b for b in text.encode("utf-8"))) for cp, text in sorted(special.items()))
    parts.append(f"static const LowerSpecial kLowerSpecial[] = {{\n{wrap(body)}}};\n")
    body = ",".join(f"{{0x{cp:X},0x{a:X},0x{b:X},{c}}}" for cp, a, b, c in decomp)
    parts.append(f"static const Decomposition kDecomposition[] = {{\n{wrap(body)}}};\n")
    body = ",".join(f"{{0x{lo:X},0x{hi:X},{value}}}" for lo, hi, value in ccc)
    parts.append(f"static const CombiningClass kCombiningClass[] = {{\n{wrap(body)}}};\n")
    target.write_text("".join(parts), encoding="utf-8")
    print(f"{target}: alnum={len(alnum)} decimal={len(decimal)} mark={len(mark)} punct_space={len(punct_space)} "
          f"cased={len(cased_ranges)} case_ignorable={len(ignorable_ranges)} lower={len(runs)}+{len(special)} decomp={len(decomp)} ccc={len(ccc)}")


if __name__ == "__main__":
    main()
